@startuml

!unquoted procedure resource($type)
  class $type << (R, SandyBrown) >>
!endprocedure
!unquoted procedure collection($name, $type)
  $name *-- $type
  object $name
!endprocedure

skinparam default {
  fontName "Roboto Mono"
  fontSize 12
}
skinparam linetype ortho

resource(Certificate) {
  [revocation_state]
  Revoke(revocation_state)
  ReleaseHold()
}
resource(PublicKey) {
  certificate
  Update(public_key)
}

resource(Duchy) {
}
resource(DataProvider) {
  Get()
}
resource(MeasurementConsumer) {
  owners
  Get()
}
resource(Measurement) {
  measurement_spec
  requisition_specs
  state
  result
}
resource(Account) {
  identity
  Update(account)
}

together {
  collection(duchies, Duchy) {
  }
  collection(dataProviders, DataProvider) {
    Create(data_provider)
  }
  collection(measurementConsumers, MeasurementConsumer) {
    Create(measurementConsumer)
  }
  collection(accounts, Account) {
    Create(account)
  }
}

collection(certificates, Certificate) {
  Create(certificate)
}
collection(requisitions, Requisition) {
  List([states], [measurement_consumer])
}
collection(eventGroups, EventGroup) {
  Create(event_group)
  List([measurement_consumers])
}
collection(eventGroupMetadataDescriptors, EventGroupMetadataDescriptor) {
  Create(event_group_metadata_descriptor)
  Update(event_group_metadata_descriptor)
}
collection(measurements, Measurement) {
  Create(measurement)
  List([states])
}
collection(apiKeys, ApiKey) {
  Create(api_key)
}

resource(Requisition) {
  measurement
  requisition_spec
  state
  duchy_requisition_params
  Get()
  Refuse(refusal)
  Fulfill()
}
resource(EventGroup) {
  measurement_consumer
  metadata
  metadata_descriptor
  event_templates
  Get()
}
resource(EventGroupMetadataDescriptor) {
  descriptor_set
}
resource(ApiKey) {
  nickname
  description
  authentication_key
  Delete()
}

Certificate <.. PublicKey

Duchy *-- certificates

DataProvider *-- eventGroups
DataProvider *-- requisitions
DataProvider *-- certificates
DataProvider *-- eventGroupMetadataDescriptors
DataProvider *-- PublicKey

EventGroup .> MeasurementConsumer
EventGroup .> Certificate
EventGroup .> EventGroupMetadataDescriptor

Requisition .> EventGroup
Requisition .> Measurement
Duchy <. Requisition

MeasurementConsumer *-- measurements
MeasurementConsumer *-- certificates
MeasurementConsumer *-- PublicKey
MeasurementConsumer *-- apiKeys
MeasurementConsumer .> Account

Certificate <. Measurement

@enduml
