@startuml

!unquoted procedure resource($type)
  class $type <<(R, SandyBrown)>>
!endprocedure
!unquoted procedure collection($name, $type)
  $name *-- $type
  object $name <<collection>>
!endprocedure

hide <<collection>> circle
hide <<collection>> stereotype
hide empty members

skinparam default {
  fontName "Roboto Mono"
  fontSize 12
}
'skinparam linetype ortho
'skinparam linetype polyline

resource(Certificate) {
  [revocation_state]
  Revoke(revocation_state)
  ReleaseHold()
}
resource(PublicKey) {
  certificate
  Update(public_key)
}

resource(Duchy) {
}
resource(DataProvider) {
  Get()
}
resource(MeasurementConsumer) {
  owners
  Get()
}
resource(Account) {
  identity
  Update(account)
}

together {
  collection(duchies, Duchy) {
  }
  collection(dataProviders, DataProvider) {
    Create(data_provider)
  }
  collection(measurementConsumers, MeasurementConsumer) {
    Create(measurementConsumer)
  }
  collection(accounts, Account) {
    Create(account)
  }
}

collection(certificates, Certificate) {
  Create(certificate)
}
collection(requisitions, Requisition) {
  List([states], [measurement_consumer])
}
collection(eventGroups, EventGroup) {
  Create(event_group)
  List([measurement_consumers])
}
collection(eventGroupMetadataDescriptors, EventGroupMetadataDescriptor) {
  Create(event_group_metadata_descriptor)
  Update(event_group_metadata_descriptor)
}
collection(measurements, Measurement) {
  Create(measurement)
  List([states])
}
collection(apiKeys, ApiKey) {
  Create(api_key)
}

resource(Measurement) {
  measurement_spec
  requisition_specs
  state
  result
}
resource(Requisition) {
  measurement
  requisition_spec
  state
  duchy_requisition_params
  Get()
  Refuse(refusal)
  Fulfill()
}
resource(EventGroup) {
  measurement_consumer
  metadata
  metadata_descriptor
  event_templates
  Get()
}
resource(EventGroupMetadataDescriptor) {
  descriptor_set
}
resource(ApiKey) {
  nickname
  description
  authentication_key
  Delete()
}

Duchy *-- certificates

MeasurementConsumer *-- measurements
MeasurementConsumer *-- certificates
MeasurementConsumer *-- PublicKey
MeasurementConsumer *-- apiKeys
MeasurementConsumer .[norank].> Account

DataProvider *-- eventGroups
DataProvider *-- requisitions
DataProvider *-- certificates
DataProvider *-- eventGroupMetadataDescriptors
DataProvider *-- PublicKey

PublicKey .[norank].> Certificate

EventGroup .[norank].> MeasurementConsumer
EventGroup .[norank].> Certificate
EventGroup .[norank].> EventGroupMetadataDescriptor

Measurement .[norank].> Certificate
Measurement -[hidden]d-> requisitions

Requisition .[norank].> EventGroup
Requisition .up.> Measurement
Requisition .[norank].> Duchy

@enduml
